// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_SWaFrCGxhO71rK9gKhpTRUKfnW4Z6VA',
    appId: '1:155266534139:web:dd272b15c8b636d2a1fe5e',
    messagingSenderId: '155266534139',
    projectId: 'food-app-4b4b9',
    authDomain: 'food-app-4b4b9.firebaseapp.com',
    storageBucket: 'food-app-4b4b9.appspot.com',
    measurementId: 'G-HGXV8EQJBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNmeXGGvycxqVg32o-G8Ui3fMx5mZlVmY',
    appId: '1:155266534139:android:089f8d824e6466bba1fe5e',
    messagingSenderId: '155266534139',
    projectId: 'food-app-4b4b9',
    storageBucket: 'food-app-4b4b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYH8pVfT_fth2y4_YG-vRweTxe5eZCglY',
    appId: '1:155266534139:ios:438d345b09db35f4a1fe5e',
    messagingSenderId: '155266534139',
    projectId: 'food-app-4b4b9',
    storageBucket: 'food-app-4b4b9.appspot.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYH8pVfT_fth2y4_YG-vRweTxe5eZCglY',
    appId: '1:155266534139:ios:438d345b09db35f4a1fe5e',
    messagingSenderId: '155266534139',
    projectId: 'food-app-4b4b9',
    storageBucket: 'food-app-4b4b9.appspot.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_SWaFrCGxhO71rK9gKhpTRUKfnW4Z6VA',
    appId: '1:155266534139:web:1ea2c2f2d8d45f9ea1fe5e',
    messagingSenderId: '155266534139',
    projectId: 'food-app-4b4b9',
    authDomain: 'food-app-4b4b9.firebaseapp.com',
    storageBucket: 'food-app-4b4b9.appspot.com',
    measurementId: 'G-NW8WBLW9PC',
  );
}
